// Using logarithms to represent vast time scales to avoid BigInt limitations.
const log10YearInSeconds = Math.log10(31536000); // ~7.4988

export const timePeriods = [
    { log10s: log10YearInSeconds + 3e303 + 3, label: 'centillion-illion years' },
    { log10s: log10YearInSeconds + 3e273 + 3, label: 'nonagintillion-illion years' },
    { log10s: log10YearInSeconds + 3e243 + 3, label: 'octogintillion-illion years' },
    { log10s: log10YearInSeconds + 3e213 + 3, label: 'septuagintillion-illion years' },
    { log10s: log10YearInSeconds + 3e183 + 3, label: 'sexagintillion-illion years' },
    { log10s: log10YearInSeconds + 3e153 + 3, label: 'quinquagintillion-illion years' },
    { log10s: log10YearInSeconds + 3e123 + 3, label: 'quadragintillion-illion years' },
    { log10s: log10YearInSeconds + 3e100 + 3, label: 'googol-illion years' },
    { log10s: log10YearInSeconds + 1e100, label: 'Googolplex years' }, // A googolplex is 10^googol
    { log10s: log10YearInSeconds + 3e93 + 3, label: 'trigintillion-illion years' },
    { log10s: log10YearInSeconds + 3e63 + 3, label: 'vigintillion-illion years' },
    { log10s: log10YearInSeconds + 3e33 + 3, label: 'decillion-illion years' },
    { log10s: log10YearInSeconds + 3e30 + 3, label: 'geopillion years' }, // Unofficial SI
    { log10s: log10YearInSeconds + 3e27 + 3, label: 'brontillion years' }, // Unofficial SI

    // Based on SI prefixes (unofficial -illion names, N = 10^x)
    { log10s: log10YearInSeconds + 3e24 + 3, label: 'yottillion years' }, // N=10^24
    { log10s: log10YearInSeconds + 3e21 + 3, label: 'zettillion years' }, // N=10^21
    { log10s: log10YearInSeconds + 3e18 + 3, label: 'exillion years' },   // N=10^18
    { log10s: log10YearInSeconds + 3e15 + 3, label: 'petillion years' },  // N=10^15
    { log10s: log10YearInSeconds + 3e12 + 3, label: 'terillion years' },  // N=10^12
    { log10s: log10YearInSeconds + 3e9 + 3, label: 'gigillion years' },   // N=10^9
    { log10s: log10YearInSeconds + 3e6 + 3, label: 'megillion years' },   // N=10^6
    
    // Filling the gap between megillion (N=10^6) and millinillion (N=1000)
    { log10s: log10YearInSeconds + 3*900000 + 3, label: 'nongentimillinillion years' },
    { log10s: log10YearInSeconds + 3*800000 + 3, label: 'octingentimillinillion years' },
    { log10s: log10YearInSeconds + 3*700000 + 3, label: 'septingentimillinillion years' },
    { log10s: log10YearInSeconds + 3*600000 + 3, label: 'sescentimillinillion years' },
    { log10s: log10YearInSeconds + 3*500000 + 3, label: 'quingentimillinillion years' },
    { log10s: log10YearInSeconds + 3*400000 + 3, label: 'quadringentimillinillion years' },
    { log10s: log10YearInSeconds + 3*300000 + 3, label: 'trecentimillinillion years' },
    { log10s: log10YearInSeconds + 3*200000 + 3, label: 'ducentimillinillion years' },
    { log10s: log10YearInSeconds + 3*100000 + 3, label: 'centimillinillion years' }, // N = 100,000

    { log10s: log10YearInSeconds + 3*90000 + 3, label: 'nonagintamillinillion years' },
    { log10s: log10YearInSeconds + 3*80000 + 3, label: 'octogintamillinillion years' },
    { log10s: log10YearInSeconds + 3*70000 + 3, label: 'septuagintamillinillion years' },
    { log10s: log10YearInSeconds + 3*60000 + 3, label: 'sexagintamillinillion years' },
    { log10s: log10YearInSeconds + 3*50000 + 3, label: 'quinquagintamillinillion years' },
    { log10s: log10YearInSeconds + 3*40000 + 3, label: 'quadragintamillinillion years' },
    { log10s: log10YearInSeconds + 3*30000 + 3, label: 'trigintamillinillion years' },
    { log10s: log10YearInSeconds + 3*20000 + 3, label: 'vigintimillinillion years' },
    { log10s: log10YearInSeconds + 3*10000 + 3, label: 'decimillinillion years' }, // N = 10,000

    { log10s: log10YearInSeconds + 3*9000 + 3, label: 'novemmillinillion years' },
    { log10s: log10YearInSeconds + 3*8000 + 3, label: 'octomillinillion years' },
    { log10s: log10YearInSeconds + 3*7000 + 3, label: 'septemillinillion years' },
    { log10s: log10YearInSeconds + 3*6000 + 3, label: 'sexmillinillion years' },
    { log10s: log10YearInSeconds + 3*5000 + 3, label: 'quinmillinillion years' },
    { log10s: log10YearInSeconds + 3*4000 + 3, label: 'quattuormillinillion years' },
    { log10s: log10YearInSeconds + 3*3000 + 3, label: 'tremillinillion years' },
    { log10s: log10YearInSeconds + 3*2000 + 3, label: 'duomillinillion years' },
    
    // Higher -illions (N = 1000 and up)
    { log10s: log10YearInSeconds + 3003, label: 'millinillion years' },
    { log10s: log10YearInSeconds + 2703, label: 'noningentillion years' },
    { log10s: log10YearInSeconds + 2403, label: 'octingentillion years' },
    { log10s: log10YearInSeconds + 2103, label: 'septingentillion years' },
    { log10s: log10YearInSeconds + 1803, label: 'sescentillion years' },
    { log10s: log10YearInSeconds + 1503, label: 'quingentillion years' },
    { log10s: log10YearInSeconds + 1203, label: 'quadringentillion years' },
    { log10s: log10YearInSeconds + 903, label: 'trecentillion years' },
    { log10s: log10YearInSeconds + 603, label: 'ducentillion years' },

    // Centillion series (N=101 to 199)
    { log10s: log10YearInSeconds + 597, label: 'nonagintinovemuncentillion years' },
    { log10s: log10YearInSeconds + 573, label: 'nonaginticentillion years' },
    { log10s: log10YearInSeconds + 543, label: 'octoginticentillion years' },
    { log10s: log10YearInSeconds + 513, label: 'septuaginticentillion years' },
    { log10s: log10YearInSeconds + 483, label: 'sexaginticentillion years' },
    { log10s: log10YearInSeconds + 453, label: 'quinquaginticentillion years' },
    { log10s: log10YearInSeconds + 423, label: 'quadraginticentillion years' },
    { log10s: log10YearInSeconds + 393, label: 'triginticentillion years' },
    { log10s: log10YearInSeconds + 363, label: 'viginticentillion years' },
    { log10s: log10YearInSeconds + 333, label: 'decicentillion years' },
    { log10s: log10YearInSeconds + 330, label: 'novencentillion years' },
    { log10s: log10YearInSeconds + 327, label: 'octocentillion years' },
    { log10s: log10YearInSeconds + 324, label: 'septencentillion years' },
    { log10s: log10YearInSeconds + 321, label: 'sexcentillion years' },
    { log10s: log10YearInSeconds + 318, label: 'quincentillion years' },
    { log10s: log10YearInSeconds + 315, label: 'quattuorcentillion years' },
    { log10s: log10YearInSeconds + 312, label: 'trescentillion years' },
    { log10s: log10YearInSeconds + 309, label: 'duocentillion years' },
    { log10s: log10YearInSeconds + 306, label: 'uncentillion years' },
    { log10s: log10YearInSeconds + 303, label: 'centillion years' },
    
    // N-illion series, from N=99 down to 2
    { log10s: log10YearInSeconds + 300, label: 'novemnonagintillion years' },
    { log10s: log10YearInSeconds + 297, label: 'octononagintillion years' },
    { log10s: log10YearInSeconds + 294, label: 'septennonagintillion years' },
    { log10s: log10YearInSeconds + 291, label: 'sexnonagintillion years' },
    { log10s: log10YearInSeconds + 288, label: 'quinnonagintillion years' },
    { log10s: log10YearInSeconds + 285, label: 'quattuornonagintillion years' },
    { log10s: log10YearInSeconds + 282, label: 'trenonagintillion years' },
    { log10s: log10YearInSeconds + 279, label: 'duononagintillion years' },
    { log10s: log10YearInSeconds + 276, label: 'unnonagintillion years' },
    { log10s: log10YearInSeconds + 273, label: 'nonagintillion years' },
    { log10s: log10YearInSeconds + 270, label: 'novemoctogintillion years' },
    { log10s: log10YearInSeconds + 267, label: 'octooctogintillion years' },
    { log10s: log10YearInSeconds + 264, label: 'septenoctogintillion years' },
    { log10s: log10YearInSeconds + 261, label: 'sexoctogintillion years' },
    { log10s: log10YearInSeconds + 258, label: 'quinoctogintillion years' },
    { log10s: log10YearInSeconds + 255, label: 'quattuoroctogintillion years' },
    { log10s: log10YearInSeconds + 252, label: 'treoctogintillion years' },
    { log10s: log10YearInSeconds + 249, label: 'duooctogintillion years' },
    { log10s: log10YearInSeconds + 246, label: 'unoctogintillion years' },
    { log10s: log10YearInSeconds + 243, label: 'octogintillion years' },
    { log10s: log10YearInSeconds + 240, label: 'novemseptuagintillion years' },
    { log10s: log10YearInSeconds + 237, label: 'octoseptuagintillion years' },
    { log10s: log10YearInSeconds + 234, label: 'septenseptuagintillion years' },
    { log10s: log10YearInSeconds + 231, label: 'sexseptuagintillion years' },
    { log10s: log10YearInSeconds + 228, label: 'quinseptuagintillion years' },
    { log10s: log10YearInSeconds + 225, label: 'quattuorseptuagintillion years' },
    { log10s: log10YearInSeconds + 222, label: 'treseptuagintillion years' },
    { log10s: log10YearInSeconds + 219, label: 'duoseptuagintillion years' },
    { log10s: log10YearInSeconds + 216, label: 'unseptuagintillion years' },
    { log10s: log10YearInSeconds + 213, label: 'septuagintillion years' },
    { log10s: log10YearInSeconds + 210, label: 'novemsexagintillion years' },
    { log10s: log10YearInSeconds + 207, label: 'octosexagintillion years' },
    { log10s: log10YearInSeconds + 204, label: 'septensexagintillion years' },
    { log10s: log10YearInSeconds + 201, label: 'sexsexagintillion years' },
    { log10s: log10YearInSeconds + 198, label: 'quinsexagintillion years' },
    { log10s: log10YearInSeconds + 195, label: 'quattuorsexagintillion years' },
    { log10s: log10YearInSeconds + 192, label: 'tresexagintillion years' },
    { log10s: log10YearInSeconds + 189, label: 'duosexagintillion years' },
    { log10s: log10YearInSeconds + 186, label: 'unsexagintillion years' },
    { log10s: log10YearInSeconds + 183, label: 'sexagintillion years' },
    { log10s: log10YearInSeconds + 180, label: 'novemquinquagintillion years' },
    { log10s: log10YearInSeconds + 177, label: 'octoquinquagintillion years' },
    { log10s: log10YearInSeconds + 174, label: 'septenquinquagintillion years' },
    { log10s: log10YearInSeconds + 171, label: 'sexquinquagintillion years' },
    { log10s: log10YearInSeconds + 168, label: 'quinquinquagintillion years' },
    { log10s: log10YearInSeconds + 165, label: 'quattuorquinquagintillion years' },
    { log10s: log10YearInSeconds + 162, label: 'trequinquagintillion years' },
    { log10s: log10YearInSeconds + 159, label: 'duoquinquagintillion years' },
    { log10s: log10YearInSeconds + 156, label: 'unquinquagintillion years' },
    { log10s: log10YearInSeconds + 153, label: 'quinquagintillion years' },
    { log10s: log10YearInSeconds + 150, label: 'novemquadragintillion years' },
    { log10s: log10YearInSeconds + 147, label: 'octoquadragintillion years' },
    { log10s: log10YearInSeconds + 144, label: 'septenquadragintillion years' },
    { log10s: log10YearInSeconds + 141, label: 'sexquadragintillion years' },
    { log10s: log10YearInSeconds + 138, label: 'quinquadragintillion years' },
    { log10s: log10YearInSeconds + 135, label: 'quattuorquadragintillion years' },
    { log10s: log10YearInSeconds + 132, label: 'trequadragintillion years' },
    { log10s: log10YearInSeconds + 129, label: 'duoquadragintillion years' },
    { log10s: log10YearInSeconds + 126, label: 'unquadragintillion years' },
    { log10s: log10YearInSeconds + 123, label: 'quadragintillion years' },
    { log10s: log10YearInSeconds + 120, label: 'novemtrigintillion years' },
    { log10s: log10YearInSeconds + 117, label: 'octotrigintillion years' },
    { log10s: log10YearInSeconds + 114, label: 'septentrigintillion years' },
    { log10s: log10YearInSeconds + 111, label: 'sextrigintillion years' },
    { log10s: log10YearInSeconds + 108, label: 'quintrigintillion years' },
    { log10s: log10YearInSeconds + 105, label: 'quattuortrigintillion years' },
    { log10s: log10YearInSeconds + 102, label: 'tretrigintillion years' },
    { log10s: log10YearInSeconds + 100, label: 'googol years' },
    { log10s: log10YearInSeconds + 99, label: 'duotrigintillion years' },
    { log10s: log10YearInSeconds + 96, label: 'untrigintillion years' },
    { log10s: log10YearInSeconds + 93, label: 'trigintillion years' },
    { log10s: log10YearInSeconds + 90, label: 'novemvigintillion years' },
    { log10s: log10YearInSeconds + 87, label: 'octovigintillion years' },
    { log10s: log10YearInSeconds + 84, label: 'septenvigintillion years' },
    { log10s: log10YearInSeconds + 81, label: 'sexvigintillion years' },
    { log10s: log10YearInSeconds + 78, label: 'quinvigintillion years' },
    { log10s: log10YearInSeconds + 75, label: 'quattuorvigintillion years' },
    { log10s: log10YearInSeconds + 72, label: 'trevigintillion years' },
    { log10s: log10YearInSeconds + 69, label: 'duovigintillion years' },
    { log10s: log10YearInSeconds + 66, label: 'unvigintillion years' },
    { log10s: log10YearInSeconds + 63, label: 'vigintillion years' },
    { log10s: log10YearInSeconds + 60, label: 'novemdecillion years' },
    { log10s: log10YearInSeconds + 57, label: 'octodecillion years' },
    { log10s: log10YearInSeconds + 54, label: 'septendecillion years' },
    { log10s: log10YearInSeconds + 51, label: 'sexdecillion years' },
    { log10s: log10YearInSeconds + 48, label: 'quindecillion years' },
    { log10s: log10YearInSeconds + 45, label: 'quattuordecillion years' },
    { log10s: log10YearInSeconds + 42, label: 'tredecillion years' },
    { log10s: log10YearInSeconds + 39, label: 'duodecillion years' },
    { log10s: log10YearInSeconds + 36, label: 'undecillion years' },
    { log10s: log10YearInSeconds + 33, label: 'decillion years' },
    { log10s: log10YearInSeconds + 30, label: 'nonillion years' },
    { log10s: log10YearInSeconds + 27, label: 'octillion years' },
    { log10s: log10YearInSeconds + 24, label: 'septillion years' },
    { log10s: log10YearInSeconds + 21, label: 'sextillion years' },
    { log10s: log10YearInSeconds + 18, label: 'quintillion years' },
    { log10s: log10YearInSeconds + 15, label: 'quadrillion years' },
    { log10s: log10YearInSeconds + 12, label: 'trillion years' },
    { log10s: log10YearInSeconds + 9, label: 'billion years' },
    { log10s: log10YearInSeconds + 6, label: 'million years' },
    { log10s: log10YearInSeconds + 3, label: 'millennia' },
    { log10s: log10YearInSeconds + 2, label: 'centuries' },
    { log10s: log10YearInSeconds + 1, label: 'decades' },

    // Standard time units
    { log10s: log10YearInSeconds, label: 'years' },
    { log10s: Math.log10(30.44 * 86400), label: 'months' }, // Average month
    { log10s: Math.log10(7 * 86400), label: 'weeks' },
    { log10s: Math.log10(86400), label: 'days' },
    { log10s: Math.log10(3600), label: 'hours' },
    { log10s: Math.log10(60), label: 'minutes' },
    { log10s: 0, label: 'seconds' },
];